#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (C) 2008,2009 Sebastian Pölsterl
#
# This file is part of GNOME DVB Daemon.
#
# GNOME DVB Daemon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GNOME DVB Daemon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNOME DVB Daemon.  If not, see <http://www.gnu.org/licenses/>.

import gnomedvb
import gtk
import gtk.gdk
from gnomedvb.ui.wizard.SetupWizard import SetupWizard
from optparse import OptionParser

gnomedvb.setup_i18n()

parser = OptionParser()
parser.add_option("--transient-for", dest="transient_for", type="long",
                  help="XID of parent window")
		  
(options, args) = parser.parse_args()

w = SetupWizard()
w.realize()

if options.transient_for:
	print "Parent window:", options.transient_for
	w.set_position(gtk.WIN_POS_CENTER_ON_PARENT)
	w.set_modal(True)
	foreign_win = gtk.gdk.window_foreign_new(options.transient_for)
	if foreign_win:
		w.window.set_transient_for(foreign_win)
	else:
		print "Could not find parent window"

w.show_all()
gtk.main ()

